apiVersion: apps/v1
kind: Deployment
metadata:
  name: gws-playground-front
  labels:
    app: gws-playground-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gws-playground-front
  template:
    metadata:
      labels:
        app: gws-playground-front
    spec:
      containers:
      - name: gws-playground-front
        image: gws-playground-front
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        env:
        - name: REACT_APP_API_URL
          value: "https://gws-playground-api.gws-playground.local.getwebstack.dev"
      restartPolicy: Always
